# Generated by Django 5.0 on 2024-01-03 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0003_rename_user_posts_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='reference',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='posts',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
