# Generated by Django 5.0 on 2024-01-03 22:43

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0004_posts_reference_posts_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
