# Generated by Django 5.0 on 2024-01-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0006_alter_posts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='reference',
            new_name='chapter',
        ),
        migrations.AddField(
            model_name='posts',
            name='source',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='posts',
            name='verse',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
