# Generated by Django 5.0 on 2024-01-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0009_rename_source_posts_book_remove_posts_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='book',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='verse',
        ),
        migrations.AddField(
            model_name='posts',
            name='reference',
            field=models.CharField(default='Quran/Bible/BG', max_length=500),
        ),
    ]
