# Generated by Django 5.0 on 2024-01-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0010_remove_posts_book_remove_posts_chapter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='reference',
            new_name='book',
        ),
        migrations.AddField(
            model_name='posts',
            name='chapter',
            field=models.CharField(default='Chapter', max_length=100),
        ),
        migrations.AddField(
            model_name='posts',
            name='verse',
            field=models.CharField(default='Verse', max_length=100),
        ),
    ]
