# Generated by Django 5.0 on 2024-01-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0012_alter_posts_text_alter_posts_verse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
