# Generated by Django 5.0 on 2024-01-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0013_alter_posts_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(),
        ),
    ]
