# Generated by Django 5.0 on 2024-01-03 20:52

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_rename_user_id_posts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='user_id',
        ),
    ]
