# Generated by Django 5.0 on 2024-01-04 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0008_alter_posts_chapter_alter_posts_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='source',
            new_name='book',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
