export const gitaChapters = {
    1: ["Arjuna Vishada Yoga", "(The Yoga of the Despondency of Arjuna)"],
    2: ["Sankhya Yoga", "(Transcendental Knowledge)"],
    3: ["Karma Yoga", "(The Yoga of Action)"],
    4: ["Jnana Yoga", "(The Yoga of Knowledge)"],
    5: ["Karma Vairagya Yoga", "(The Yoga of Renunciation of Action)"],
    6: ["Abhyasa Yoga", "(The Yoga of Practice)"],
    7: ["Paramahamsa Vijnana Yoga", "(The Yoga of Supreme Knowledge and Realization)"],
    8: ["Aksara-Parabrahman Yoga", "(The Yoga of the Imperishable Absolute)"],
    9: ["Raja-Vidya-Raja-Guhya Yoga", "(The Yoga of Royal Knowledge and Royal Secret)"],
    10: ["Vibhuti-Vistara-Yoga", "(The Yoga of Divine Glories)"],
    11: ["Visvarupa-Darsana Yoga", "(The Yoga of the Vision of the Universal Form)"],
    12: ["Bhakti Yoga", "(The Yoga of Devotion)"],
    13: ["Kshetra-Kshetragna Vibhaga Yoga", "(The Yoga of the Field and the Knower of the Field)"],
    14: ["Gunatraya-Vibhaga Yoga", "(The Yoga of the Division of the Three Gunas)"],
    15: ["Purushottama Yoga", "(The Yoga of the Supreme Divine Personality)"],
    16: ["Daivasura-Sampad-Vibhaga Yoga", "(The Yoga of the Division between the Divine and the Demonic)"],
    17: ["Sraddhatraya-Vibhaga Yoga", "(The Yoga of the Division of the Threefold Faith)"],
    18: ["Moksa-Sannyasa Yoga", "(The Yoga of Liberation and Renunciation)"]
};