# Generated by Django 4.2.7 on 2023-12-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default=None, max_length=100)),
                ('book', models.CharField(default=None)),
                ('chapter', models.IntegerField(default=None)),
                ('verse', models.CharField(default=None)),
                ('text', models.TextField(default=None)),
            ],
        ),
    ]
