# Generated by Django 5.0 on 2023-12-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='passage_id',
        ),
        migrations.AddField(
            model_name='favorites',
            name='book',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='favorites',
            name='chapter',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='favorites',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='favorites',
            name='text',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='favorites',
            name='verse',
            field=models.CharField(default=None),
        ),
    ]
