# Generated by Django 5.0 on 2024-01-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='details',
        ),
    ]
