# Generated by Django 4.2.7 on 2023-12-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_favorites_passage_id_favorites_book_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Journal',
            new_name='JournalEntries',
        ),
        migrations.DeleteModel(
            name='Passages',
        ),
        migrations.AlterField(
            model_name='favorites',
            name='verse',
            field=models.IntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
