# Generated by Django 5.0 on 2024-01-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_favorites_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='details',
            field=models.TextField(default=None),
        ),
    ]
