# Generated by Django 5.0 on 2023-12-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_passages_journal_favorites_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passages',
            name='verse',
            field=models.CharField(default=None),
        ),
    ]
