# Generated by Django 5.0 on 2023-12-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_passages_verse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passages',
            name='book',
            field=models.CharField(default=None),
        ),
    ]
