# Generated by Django 5.0 on 2023-12-31 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_favorites_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='journalentries',
            old_name='user_id',
            new_name='user',
        ),
    ]
