# Generated by Django 5.0 on 2024-01-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_rename_user_id_favorites_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='book',
            new_name='reference',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='verse',
        ),
        migrations.AddField(
            model_name='favorites',
            name='details',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='favorites',
            name='source',
            field=models.CharField(default=None),
        ),
    ]
