# Generated by Django 5.0 on 2024-01-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_rename_user_id_favorites_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='chapter',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='book',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='verse',
        ),
        migrations.AlterField(
            model_name='favorites',
            name='text',
            field=models.CharField(default=None),
        ),
    ]
