# Generated by Django 5.0 on 2024-01-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_rename_chapter_favorites_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='reference',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
