# Generated by Django 5.0 on 2024-01-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_rename_book_favorites_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentries',
            name='title',
            field=models.CharField(default='Journal entry', max_length=100),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='text',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
