# Generated by Django 5.0 on 2024-01-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_journalentries_title_alter_journalentries_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentries',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
